import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotistackProvider } from "./providers/NotistackProvider";
import NextTopLoader from "nextjs-toploader";
import SplashProvider from "./providers/SplashProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="coffee" className="noisy-bg min-h-screen" lang="fa">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        dir="rtl"
      >
        <NextTopLoader
          color="#DB924C"
          initialPosition={0.08}
          crawlSpeed={200}
          height={4}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
        />
        <SplashProvider>
          <NotistackProvider>{children}</NotistackProvider>
        </SplashProvider>
      </body>
    </html>
  );
}
